# Generated by Django 4.0.5 on 2022-08-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('link_facebook', models.URLField()),
                ('link_instagram', models.URLField()),
                ('link_twetter', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
