# Generated by Django 4.0.5 on 2022-08-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_active_accountverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verification_account',
            field=models.BooleanField(default=False),
        ),
    ]
