# Generated by Django 4.0.5 on 2022-08-17 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_is_verification_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountverification',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
