# Generated by Django 4.0.5 on 2022-08-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_email_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
