# Generated by Django 4.1 on 2022-09-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
    ]
