# Generated by Django 4.0.5 on 2022-08-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_appointmen_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(default=5000),
            preserve_default=False,
        ),
    ]
