# Generated by Django 4.0.5 on 2022-08-23 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmen',
            name='date_appointmen',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
