# Generated by Django 4.0.5 on 2022-08-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmen',
            name='motif',
            field=models.CharField(default='Mal de tête', max_length=150),
            preserve_default=False,
        ),
    ]
