# Generated by Django 4.1 on 2022-08-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_appointmen_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(default='', upload_to='photo_service'),
            preserve_default=False,
        ),
    ]
