# Generated by Django 4.1 on 2022-08-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_service_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmen',
            name='date_appointmen',
            field=models.DateField(),
        ),
    ]
