# Generated by Django 4.1 on 2022-08-30 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_appointmen_date_appointmen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
    ]
